import type { CareerProfileInput } from "@/schemas/career-profile";

export function createMockGraduateProfile(userId: string): CareerProfileInput {
  return {
    userId,
    targetStatus: "seeking_fulltime",
    targetRoles: ["Java 后端开发", "软件开发工程师"],
    targetCities: ["杭州", "上海", "南京"],
    expectedSalaryMin: 12000,
    expectedSalaryMax: 18000,
    personalSummary:
      "计算机科学与技术本科应届生，熟悉 Java、Spring Boot、MySQL 与 Redis，有校园项目和互联网实习经历，关注高并发后端服务与业务工程化。",
    basicInfo: {
      realName: "李明",
      phone: "13800138000",
      email: "liming@example.com",
      location: "江苏南京",
      githubUrl: "https://github.com/example-student",
      portfolioUrl: "",
      linkedinUrl: "",
      personalWebsite: "https://example-student.dev",
    },
    educationItems: [
      {
        school: "南京邮电大学",
        major: "计算机科学与技术",
        degree: "本科",
        startDate: new Date("2022-09-01"),
        endDate: new Date("2026-06-30"),
        gpa: "3.65/4.0",
        ranking: "前 15%",
        courses: ["数据结构", "操作系统", "计算机网络", "数据库系统", "软件工程"],
        honors: ["校二等奖学金", "优秀学生干部"],
      },
    ],
    skillItems: [
      {
        name: "Java",
        category: "programming_language",
        level: "advanced",
        evidence: "项目主语言与实习开发语言",
        yearsOfExperience: 2,
      },
      {
        name: "Spring Boot",
        category: "framework",
        level: "intermediate",
        evidence: "完成电商订单服务与实习需求开发",
        yearsOfExperience: 1.5,
      },
      {
        name: "MySQL",
        category: "database",
        level: "intermediate",
        evidence: "负责表设计、索引优化与慢查询排查",
        yearsOfExperience: 1.5,
      },
      {
        name: "Redis",
        category: "database",
        level: "intermediate",
        evidence: "用于缓存热点商品与验证码限流",
        yearsOfExperience: 1,
      },
    ],
    projectItems: [
      {
        name: "校园二手交易平台",
        role: "后端负责人",
        startDate: new Date("2025-03-01"),
        endDate: new Date("2025-06-30"),
        background: "校内闲置物品交易信息分散，缺少统一发布与沟通平台。",
        goal: "建设支持商品发布、搜索、收藏、私信和订单流转的 Web 系统。",
        responsibilities: ["设计用户、商品、订单核心表结构", "实现商品检索、订单状态机和权限校验"],
        techStack: ["Java", "Spring Boot", "MySQL", "Redis", "Docker"],
        highlights: ["使用 Redis 缓存热门商品列表", "通过唯一索引和事务避免重复下单"],
        results: "完成 MVP 并在学院内测使用。",
        metrics: ["内测用户 200+", "接口 P95 响应时间低于 180ms"],
        links: ["https://github.com/example-student/campus-market"],
      },
      {
        name: "在线判题系统",
        role: "后端开发",
        startDate: new Date("2024-09-01"),
        endDate: new Date("2024-12-30"),
        background: "课程作业需要自动化评测代码提交。",
        goal: "支持题目管理、代码提交、异步评测和结果查询。",
        responsibilities: ["实现提交队列与评测结果回写", "编写 REST API 与基础单元测试"],
        techStack: ["Java", "Spring Boot", "RabbitMQ", "MySQL"],
        highlights: ["拆分提交服务与评测服务", "增加超时控制和状态追踪"],
        results: "支撑课程大作业评测。",
        metrics: ["累计提交 3000+", "评测失败自动重试"],
        links: [],
      },
    ],
    experienceItems: [
      {
        company: "杭州某互联网科技有限公司",
        department: "交易平台研发部",
        role: "后端开发实习生",
        employmentType: "internship",
        startDate: new Date("2025-07-01"),
        endDate: new Date("2025-10-31"),
        responsibilities: ["参与商家后台优惠券模块迭代", "补充接口测试并修复线上边界问题"],
        achievements: ["将优惠券列表查询耗时降低约 35%", "独立完成 3 个小需求上线"],
        techStack: ["Java", "Spring Boot", "MyBatis", "MySQL", "Redis"],
        businessImpact: "提升商家后台运营配置效率。",
        metrics: ["慢查询从 620ms 优化到 400ms 内"],
      },
    ],
    certificateItems: [
      {
        name: "大学英语六级",
        issuer: "教育部教育考试院",
        issuedAt: new Date("2024-06-15"),
        expiresAt: null,
        credentialUrl: "",
      },
    ],
    awardItems: [
      {
        name: "蓝桥杯 Java 软件开发省赛二等奖",
        issuer: "蓝桥杯大赛组委会",
        level: "省级",
        awardedAt: new Date("2025-04-20"),
        description: "Java 软件开发方向。",
      },
    ],
    evidenceItems: [
      {
        type: "url",
        title: "GitHub 项目集合",
        url: "https://github.com/example-student",
        description: "包含校园交易平台和在线判题系统源码。",
        relatedEntityType: "profile",
        relatedEntityId: "",
      },
    ],
  };
}
