import type { ResumeProfile } from "../services/resume-generator";
import type { JDAnalysisResult } from "../types/jd";

export const fictionalSmokeProfile = {
  id: "fictional-smoke-profile",
  userId: null,
  targetRoles: ["AI 应用开发实习生"],
  targetCities: ["上海"],
  expectedSalaryMin: null,
  expectedSalaryMax: null,
  expectedSalaryMonths: null,
  jobSearchStatus: "actively_looking",
  availabilityDate: null,
  personalSummary: "信息与计算科学本科生，具备 TypeScript、Python、PostgreSQL、Next.js、Git 和基础自动化测试能力。",
  basicInfo: {
    realName: "演示候选人",
    phone: "000-0000-0000",
    email: "demo@example.invalid",
    location: "虚构地点",
    githubUrl: null,
    linkedinUrl: null,
    portfolioUrl: null,
    personalWebsite: null,
  },
  educationItems: [{
    school: "示例大学（虚构）",
    major: "信息与计算科学",
    degree: "本科",
    startDate: null,
    endDate: null,
    gpa: null,
    ranking: null,
    courses: [],
    honors: [],
  }],
  skillItems: [
    { name: "TypeScript", level: "基础", evidence: "课程任务管理系统" },
    { name: "Python", level: "基础", evidence: "课程学习" },
    { name: "PostgreSQL", level: "基础", evidence: "课程任务管理系统" },
    { name: "Next.js", level: "基础", evidence: "课程任务管理系统" },
    { name: "Git", level: "基础", evidence: "项目版本管理" },
    { name: "自动化测试", level: "基础", evidence: "基础单元测试" },
  ],
  projectItems: [{
    name: "课程任务管理系统",
    role: "课程项目成员",
    background: "课程项目",
    goal: "实现任务管理功能",
    responsibilities: ["任务创建、编辑、筛选和状态管理", "使用 Zod 进行输入校验", "编写基础单元测试"],
    techStack: ["Next.js", "TypeScript", "PostgreSQL", "Zod", "Git"],
    highlights: [],
    results: null,
    metrics: [],
    links: [],
    startDate: null,
    endDate: null,
  }],
  experienceItems: [],
  certificateItems: [],
  awardItems: [],
  evidenceItems: [],
  languageItems: [],
  preference: null,
} as unknown as ResumeProfile;

export const fictionalSmokeJD: JDAnalysisResult = {
  targetRole: "AI 应用开发实习生",
  seniorityLevel: "intern",
  internshipDuration: "",
  conversionOpportunity: "",
  candidateProfile: ["具备基础 Web 开发能力的在校生"],
  coreResponsibilities: [
    "使用 TypeScript 或 Python 开发 AI 应用",
    "对接 OpenAI-compatible LLM API",
    "使用数据库保存业务数据",
    "编写自动化测试",
  ],
  hardSkills: ["TypeScript", "Python", "OpenAI-compatible LLM API", "数据库", "Web 开发", "自动化测试"],
  softSkills: [],
  experienceRequirements: [],
  educationRequirements: [],
  bonusPoints: [],
  keywords: ["TypeScript", "Python", "LLM API", "PostgreSQL", "Web", "自动化测试"],
  matchScore: 65,
  scoreBreakdown: {
    hardSkillScore: 65,
    projectMatchScore: 55,
    experienceMatchScore: 20,
    educationMatchScore: 80,
    keywordCoverageScore: 70,
  },
  matchedPoints: ["TypeScript", "Python", "PostgreSQL", "Next.js", "基础自动化测试"],
  gaps: ["没有 OpenAI-compatible LLM API 实践", "没有 AI 项目经验", "没有实习经历"],
  riskWarnings: ["不得把岗位要求写成候选人已有能力"],
  resumeRewriteSuggestions: ["强调已有 Web、数据库和测试事实", "将 LLM API 能力列为待补足项"],
};

export const fictionalSmokeBaseResume = [
  "# 演示候选人",
  "信息与计算科学本科生。",
  "技能：TypeScript、Python、PostgreSQL、Next.js、Git、基础自动化测试。",
  "课程项目：使用 Next.js 和 PostgreSQL 开发任务管理系统，实现任务创建、编辑、筛选和状态管理，使用 Zod 校验输入并编写基础单元测试。",
].join("\n");

export const fictionalSmokeJob = {
  company: "示例科技有限公司（虚构）",
  role: "AI 应用开发实习生",
  requirements: ["TypeScript", "Python", "OpenAI-compatible LLM API", "数据库", "自动化测试", "Web 开发"],
};
